jadwal/story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_3.urls')),
    path('story_1/', include('story_1.urls')),
]

jadwal/story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

jadwal/story_3/urls.py
from django.urls import path
from . import views

app_name = 'story_3'

urlpatterns = [
    path('', views.index, name='index'),
    path('CV', views.CV_page, name='CV_page'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_3.urls')),
    path('story_1/', include('story_1.urls')),
]

story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

story_3/urls.py
from django.urls import path
from . import views

app_name = 'story_3'

urlpatterns = [
    path('', views.index, name='index'),
    path('CV', views.CV_page, name='CV_page'),
    path('time/<str:timeChange>', views.time, name='time'),
    path('form', views.jadwal, name='jadwal'),
    # dilanjutkan ...
]

jadwal/story_1/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

story_3/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Jadwal(models.Model):
    mata_kuliah = models.CharField(blank=False, max_length= 100)
    dosen_pengajar = models.CharField(blank=False, max_length= 100)
    jumlah_sks = models.CharField(blank=False, max_length= 100)
    semester_tahun = models.CharField(blank=False, max_length= 100)
    ruang_kelas = models.CharField(blank=False, max_length= 100)
    deskripsi = models.CharField(blank=False, max_length= 100)

story_3/forms.py
from django import forms

class formulir(forms.Form):
    mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    dosen_pengajar = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Dosen Pengajar',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True
    }))
    semester_tahun = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester dan Tahun',
        'type' : 'text',
        'required' : True
    }))
    ruang_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Ruang Kelas',
        'type' : 'text',
        'required' : True
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))

jadwal/story_1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    print("TESTTTT")
    return render(request, 'story_1/index_story_1.html')

jadwal/story_3/views.py
from django.shortcuts import render, redirect
from .models import Schedule, ScheduleForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def CV_page(request):
    return render(request, "CV_page.html")


def form(request):
    if request.method == "POST":
        schedform = ScheduleForm(request.POST)

        if schedform.is_valid():
            schedform.save()
        
            return redirect("story_3:index")

    else:
        schedform = ScheduleForm()

    return render(request, "form.html", {'schedform':schedform})
            

story_1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    print("TESTTTT")
    return render(request, 'story_1/index_story_1.html')

story_3/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import formulir
import datetime

# Create your views here.
def index(request):
    return render(request, 'index.html')

def CV_page(request):
    return render(request, 'CV_page.html')

def time(request, timeChange):
    timeChange = int(timeChange)
    time = datetime.datetime.now() + datetime.timedelta(hours=timeChange)
    return render(request, 'time.html', {"finalTime" : time })

def jadwal(request):
    if(request.method == "POST"):
        tmp = formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = Jadwal()
            tmp2.nama_kegiatan = tmp.cleaned_data["mata_kuliah"]
            tmp2.jumlah_sks = tmp.cleaned_data["jumlah_sks"]
            tmp2.semester_tahun = tmp.cleaned_data["semester_tahun"]
            tmp2.dosen_pengajar = tmp.cleaned_data["dosen_pengajar"]
            tmp2.ruang_kelas = tmp.cleaned_data["ruang_kelas"]
            tmp2.deskripsi = tmp.cleaned_data["deskripsi"]
            tmp2.save()
        return redirect("/form")
    else:
        tmp = formulir()
        tmp2 = Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2
        }
        return render(request, 'form.html', tmp_dictio)

def delete(request, pk):
    if(request.method == "POST"):
        tmp = formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = Jadwal()
            tmp2.nama_kegiatan = tmp.cleaned_data["mata_kuliah"]
            tmp2.jumlah_sks = tmp.cleaned_data["jumlah_sks"]
            tmp2.semester_tahun = tmp.cleaned_data["semester_tahun"]
            tmp2.dosen_pengajar = tmp.cleaned_data["dosen_pengajar"]
            tmp2.ruang_kelas = tmp.cleaned_data["ruang_kelas"]
            tmp2.deskripsi = tmp.cleaned_data["deskripsi"]
            tmp2.save()
        return redirect("/form")
    else:
        Jadwal.objects.filter(pk = pk).delete()
        tmp = formulir()
        tmp2 = Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2
        }
        return render(request, 'form.html', tmp_dictio)

jadwal/story_3/templates/CV_page.html
{% load static %}
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<title>
			Story about Fariz
		</title>

		<link rel="stylesheet" href="{% static 'style.css' %}">

		<style>
		@import url('https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,700,800|Playfair+Display:400,700,800&display=swap');</style>
    </head>

    <body>
<!-- 		<div id="navbar">
			<a href="#home">Home</a>
			<a href="#education">Education</a>
			<a href="#experience">Experience</a>
			<a href="#interest">Interest</a>
			<a href="#contact">Contact</a>
		</div> -->
		<div class="titletnr">This is my latest CV</div><a href="{% url 'story_3:index' %}">   click here to go back to main page</a>
		<div><img src="{% static 'CV/CV1.jpg' %}"><img src="{% static 'CV/CV2.jpg' %}"><img src="{% static 'CV/CV3.jpg' %}"><img src="{% static 'CV/CV4.jpg' %}"><img src="{% static 'CV/CV5.jpg' %}"><img src="{% static 'CV/CV6.jpg' %}"><img src="{% static 'CV/CV7.jpg' %}"></div>

		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
				<script>$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})</script>
	</body>
</html>

jadwal/story_3/templates/index.html
{% load static %}
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<title>
			Story about Fariz
		</title>

		<link rel="stylesheet" href="{% static 'style.css' %}">

		<style>
		@import url('https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,700,800|Playfair+Display:400,700,800&display=swap');</style>
    </head>

    <body>
		<div id="navbar">
			<a href="#home">Home</a>
			<a href="#education">Education</a>
			<a href="#experience">Experience</a>
			<a href="#interest">Interest</a>
			<a href="#contact">Contact</a>
			<a href="{% url 'story_1:index' %}">Story 1</a>
			<a href="{% url 'story_3:index' %}">Story 4</a>
		</div>

    	<section id="home" class="page">
	    	<p class="avatar"><img src="{% static 'avt.png' %}" alt="Avatar" style="margin-top: 14vh"></p>
	    	<div class="title", style="text-align: center;">fariz habibie permana</div>
	    	<div class="subtitle">A tech-savvy born in February 1st 2002, currently studying at Computer Science Faculty in University of Indonesia</div>
	    	<div style="padding-top: 4%"><a class="more" href="#education">more</a></div>
	    </section>

	    <section id="education" class="page">
	    	<div class="titletnr" style="text-align: left">my education.</div>

	    	<ul>
				<li><p class="tipe1" style="margin-top: 1vh">2005 — 2007</p></li>
				<li><p class="tipe2">TK Islam Amanah Bangsa (ASA)</p></li>
				<li><p class="tipe1">2007 — 2013</p></li>
				<li><p class="tipe2">SD Islam Amanah Bangsa (ASA)</p></li>
				<li><p class="tipe1">2013 — 2016</p></li>
				<li><p class="tipe2">SMP Negeri 1 Kota Bekasi</p></li>
				<li><p class="tipe1">2016 — 2019</p></li>
				<li><p class="tipe2">SMA Negeri 1 Kota Bekasi</p></li>
				<li><p class="tipe1">2019 — Present</p></li>
				<li><p class="tipe2">SMA Negeri 1 Kota Bekasi</p></li>
			</ul>

			<div style="padding-top: 1.5%"><a class="more" href="#experience">more</a></div>
			<div class="div-arrow"><p class="arrow"><img src="{% static 'arrow-grey.png' %}" alt="arrow"></p></div>
			<div class="circle" style="	right:-15vw; top:1vh;"></div>
	    </section>

	 	<section id="experience" class="page">
	    	<div class="titletnr" style="text-align: left">my experience.</div>

	    	<ul class="edu-content">
				<li><p class="tipe3" style="margin-top: 1vh">Public Relation Staff at Open House Fasilkom UI 2019</p></li>
				<li><p class="tipe4">September — 2019 November 2019</p></li>
				<li><p class="tipe5">My team and I announced and explained about the event to several schools.</p></li>
			</ul>

			<ul class="edu-content">
				<li><p class="tipe3">Master of Ceremonies at Wisuda Ganjil 2019/2020 Fasilkom UI</p></li>
				<li><p class="tipe4">January 2020</p></li>
				<li><p class="tipe5">I lead and conducted the graduation event.</p></li>
			</ul>

			<ul class="edu-content">
				<li><p class="tipe3">Human Resource Representative of Event Division at PERAK 2020</p></li>
				<li><p class="tipe4">January 2020 — Present</p></li>
				<li><p class="tipe5">I recruited and administrate the staff of Event Division.</p></li>
			</ul>

			<div style="padding-top: 1.5%"><a class="more" href="#interest">more</a></div>
			<div class="div-arrow"><p class="arrow"><img src="{% static 'arrow-grey.png' %}" alt="arrow"></p></div>
	    </section>

	   	<div class="circle" style="	left:-15vw; margin-top:201vh"></div>

	   	<section id="interest" class="page">
	   		<div class="titletnr" style="text-align: left">things i'm interested in.</div>
	   		<div class="icon"><img src="{% static 'code.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i like to code, especcialy in Python</a></div>

	   		<div class="icon"><img src="{% static 'design.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i’ve been designing since i was 11</a></div>

	   		<div class="icon"><img src="{% static 'music.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i always have my passion in classical music</a></div>

	   		<div class="row">
		   		<div class="col"> <!-- ka WH, ini yg make bootstrapnya ya kak. maaf saya lupa pake bootstrap dari awal dan waktunya udah mepet huhu :"( -->
		   			<div><a class="more" href="#contact">more</a></div>
		   			<div class="titletnr" style="text-align: right; font-style: italic; margin-top: 0; float: right; font-size:8.5vh">cogito ergo sum.</div>
		   		</div>
	   		</div>
	   	</section>

	   	<section id="contact" class="page">
	   		<div class="titletnr" style="text-align: left">contact me.</div>
	   		<div class="boxes">
	   			<div class="box box-ig"><a style="display: block; height: 100%", href="https://www.instagram.com/hpfariz/" target="_blank"><img src="{% static 'instagram1.png' %}", class="logo"></a></div>
	   			<div class="box box-linkedin"><a style="display: block; height: 100%", href="https://www.linkedin.com/in/hpfariz" target="_blank"><img src="{% static 'linkedin1.png' %}", class="logo"></a></div>
	   			<div class="box box-tw"><a style="display: block; height: 100%", href="https://twitter.com/farizfhp" target="_blank"><img src="{% static 'twitter1.png' %}", class="logo", style="margin-top: 3.5vw"></a></div>
	   		</div>
	   	</section>
		
		<br><br><br>
		<div class="titletnr" style="text-align: left; margin-top: 500vh; height:40vh">contact me.
		<div>
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
			  Click here to see some cats.
			</button>

			<!-- Modal -->
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="exampleModalLabel">some cats for you.</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        
			      	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
					  <div class="carousel-inner">
					    <div class="carousel-item active">
					      <img class="d-block w-100" src="{% static 'cats/cat1.jpg' %}" alt="First slide">
					    </div>
					    <div class="carousel-item">
					      <img class="d-block w-100" src="{% static 'cats/cat2.jpg' %}" alt="Second slide">
					    </div>
					    <div class="carousel-item">
					      <img class="d-block w-100" src="{% static 'cats/cat3.jpg' %}" alt="Third slide">
					    </div>
					  </div>
					  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
					    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
					    <span class="sr-only">Previous</span>
					  </a>
					  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
					    <span class="carousel-control-next-icon" aria-hidden="true"></span>
					    <span class="sr-only">Next</span>
					  </a>
					</div>

			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div>
		</div>
		<div><a href="{% url 'story_3:CV_page' %}" style="font-size: 3vw">click me to view my latest resume</a></div>
		<div style="height: 50vh"></div>

		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
				<script>$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})</script>
    </body> 
</html>

story_3/templates/includes/navbar.html
<head>
	<style>
		a:link {
		  text-decoration: none;
		}

		a:visited {
		  text-decoration: none;
		}

		a:hover {
		  text-decoration: none;
		  color: #A8A8A8;
		}

		a:active {
		  text-decoration: none;
		  color: black;
		}

		ul {
		  list-style-type: none;
		  margin: 0;
		  padding: 0;
		  overflow: hidden!important;
		}

		#navbar {
		  overflow: hidden;
		  background-color: rgba(229, 229, 229, 0.5);
		  /*margin-left:22vw;*/
		  width: 100%;
		  justify-content: center;
		  position: fixed;
		  top:0;
		  z-index: 999;
		  display: flex;
		}

		/* Navbar links */
		#navbar a {
		  float: left;
		  display: block;
		  font-family: Montserrat, sans-serif;
		  font-weight: 700;
		  text-align: center;
		  padding: 14px 16px;
		  margin-left: 2vw;
		  margin-right: 2vw;
		  text-decoration: none;

		  color: #FF7315; opacity: 1;
		}

		/* The sticky class is added to the navbar with JS when it reaches its scroll position */
		.sticky {
		  position: fixed;
		  top: 0;
		  width: 100%;
		}

		.sticky + .content {
		  padding-top: 7vh;
		}
		</style>
		<body>
			<div id="navbar">
				<a href="#home">Home</a>
				<a href="#education">Education</a>
				<a href="#experience">Experience</a>
				<a href="#interest">Interest</a>
				<a href="#contact">Contact</a>
				<a href="{% url 'story_1:index' %}">Story 1</a>
				<a href="{% url 'story_3:jadwal' %}">Tambah Jadwal</a>
			</div>
		</body>

story_3/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
	<section id="home" class="page">
    	<p class="avatar"><img src="{% static 'avt.png' %}" alt="Avatar" style="margin-top: 14vh"></p>
    	<div class="title", style="text-align: center;">fariz habibie permana</div>
    	<div class="subtitle">A tech-savvy born in February 1st 2002, currently studying at Computer Science Faculty in University of Indonesia</div>
    	<div style="padding-top: 4%"><a class="more" href="#education">more</a></div>
    </section>

    <section id="education" class="page">
    	<div class="titletnr" style="text-align: left">my education.</div>

    	<ul>
			<li><p class="tipe1" style="margin-top: 1vh">2005 — 2007</p></li>
			<li><p class="tipe2">TK Islam Amanah Bangsa (ASA)</p></li>
			<li><p class="tipe1">2007 — 2013</p></li>
			<li><p class="tipe2">SD Islam Amanah Bangsa (ASA)</p></li>
			<li><p class="tipe1">2013 — 2016</p></li>
			<li><p class="tipe2">SMP Negeri 1 Kota Bekasi</p></li>
			<li><p class="tipe1">2016 — 2019</p></li>
			<li><p class="tipe2">SMA Negeri 1 Kota Bekasi</p></li>
			<li><p class="tipe1">2019 — Present</p></li>
			<li><p class="tipe2">SMA Negeri 1 Kota Bekasi</p></li>
		</ul>

		<div style="padding-top: 1.5%"><a class="more" href="#experience">more</a></div>
		<div class="div-arrow"><p class="arrow"><img src="{% static 'arrow-grey.png' %}" alt="arrow"></p></div>
		<div class="circle" style="	right:-15vw; top:1vh;"></div>
    </section>

 	<section id="experience" class="page">
    	<div class="titletnr" style="text-align: left">my experience.</div>

    	<ul class="edu-content">
			<li><p class="tipe3" style="margin-top: 1vh">Public Relation Staff at Open House Fasilkom UI 2019</p></li>
			<li><p class="tipe4">September — 2019 November 2019</p></li>
			<li><p class="tipe5">My team and I announced and explained about the event to several schools.</p></li>
		</ul>

		<ul class="edu-content">
			<li><p class="tipe3">Master of Ceremonies at Wisuda Ganjil 2019/2020 Fasilkom UI</p></li>
			<li><p class="tipe4">January 2020</p></li>
			<li><p class="tipe5">I lead and conducted the graduation event.</p></li>
		</ul>

		<ul class="edu-content">
			<li><p class="tipe3">Human Resource Representative of Event Division at PERAK 2020</p></li>
			<li><p class="tipe4">January 2020 — Present</p></li>
			<li><p class="tipe5">I recruited and administrate the staff of Event Division.</p></li>
		</ul>

		<div style="padding-top: 1.5%"><a class="more" href="#interest">more</a></div>
		<div class="div-arrow"><p class="arrow"><img src="{% static 'arrow-grey.png' %}" alt="arrow"></p></div>
    </section>

   	<div class="circle" style="	left:-15vw; margin-top:201vh"></div>

   	<section id="interest" class="page">
   		<div class="titletnr" style="text-align: left">things i'm interested in.</div>
   		<div class="icon"><img src="{% static 'code.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i like to code, especcialy in Python</a></div>

   		<div class="icon"><img src="{% static 'design.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i’ve been designing since i was 11</a></div>

   		<div class="icon"><img src="{% static 'music.png' %}"><a class="tipe4" style="font-style: normal; font-size: 2.5vw; margin-left: 10%">i always have my passion in classical music</a></div>

   		<div class="row">
	   		<div class="col"> <!-- ka WH, ini yg make bootstrapnya ya kak. maaf saya lupa pake bootstrap dari awal dan waktunya udah mepet huhu :"( -->
	   			<div><a class="more" href="#contact">more</a></div>
	   			<div class="titletnr" style="text-align: right; font-style: italic; margin-top: 0; float: right; font-size:8.5vh">cogito ergo sum.</div>
	   		</div>
   		</div>
   	</section>

   	<section id="contact" class="page">
   		<div class="titletnr" style="text-align: left">contact me.</div>
   		<div class="boxes">
   			<div class="box box-ig"><a style="display: block; height: 100%", href="https://www.instagram.com/hpfariz/" target="_blank"><img src="{% static 'instagram1.png' %}", class="logo"></a></div>
   			<div class="box box-linkedin"><a style="display: block; height: 100%", href="https://www.linkedin.com/in/hpfariz" target="_blank"><img src="{% static 'linkedin1.png' %}", class="logo"></a></div>
   			<div class="box box-tw"><a style="display: block; height: 100%", href="https://twitter.com/farizfhp" target="_blank"><img src="{% static 'twitter1.png' %}", class="logo", style="margin-top: 3.5vw"></a></div>
   		</div>
   	</section>
	
	<br><br><br>
	<div class="titletnr" style="text-align: left; margin-top: 500vh; height:40vh">contact me.
	<div>
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
		  Click here to see some cats.
		</button>

		<!-- Modal -->
		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">some cats for you.</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
		        
		      	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
				  <div class="carousel-inner">
				    <div class="carousel-item active">
				      <img class="d-block w-100" src="{% static 'cats/cat1.jpg' %}" alt="First slide">
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="{% static 'cats/cat2.jpg' %}" alt="Second slide">
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="{% static 'cats/cat3.jpg' %}" alt="Third slide">
				    </div>
				  </div>
				  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
				    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
				    <span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>

		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
	<div><a href="{% url 'story_3:CV_page' %}" style="font-size: 3vw">click me to view my latest resume</a></div>
	<div style="height: 50vh"></div>
	
{% endblock %}

story_3/templates/time.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
	<div class ="titletnr">Time : {{finalTime}}</div>
{% endblock %}